#!/bin/bash

cleanup() {
	lf-ueberzug-cleaner
	kill "$UEBERZUGPID"
	pkill -f "tail -f $LF_UEBERZUG_TEMPDIR/fifo"
	rm -rf "$LF_UEBERZUG_TEMPDIR"
}

lfcd() {
    export LF_SHELLCD_TEMPDIR="$(mktemp -d -t lf-shellcd-XXXXXX)"

    /usr/bin/lf -last-dir-path "$LF_SHELLCD_TEMPDIR/lastdir" "$@"

    if [ -e "$LF_SHELLCD_TEMPDIR/changecwd" ] && \
        dir="$(cat "$LF_SHELLCD_TEMPDIR/lastdir")" 2>/dev/null; then
        cd "$dir"
    fi

    rm -rf "$LF_SHELLCD_TEMPDIR"
    unset LF_SHELLCD_TEMPDIR
}

trap cleanup INT HUP

# Set up temporary directory.
export LF_UEBERZUG_TEMPDIR="$(mktemp -d -t lf-ueberzug-XXXXXX)"

# Launch ueberzug.
mkfifo "$LF_UEBERZUG_TEMPDIR/fifo"
tail -f "$LF_UEBERZUG_TEMPDIR/fifo" | ueberzug layer --silent &
UEBERZUGPID=$!

# Add this script's directory to PATH so that the lf config will find
# lf-ueberzug-cleaner and lf-ueberzgu-previewer. If no startup directory is
# provided, start lf in the examples directory.
export PATH="$PATH:${ZSH_ARGZERO:A:h}"
lfcd "$@"
cleanup
